version: "3"
services:
  db:
    image: postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: dockerdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - /pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    container_name: idea-container-db
